export enum sagasConstants {
   REQUEST_PRODUCTS_SAGA = "REQUEST_PRODUCTS_SAGA",
   REQUEST_PRODUCT_SAGA = "REQUEST_PRODUCT_SAGA",
   REQUEST_COUNTRIES_SAGA = "REQUEST_COUNTRIES_SAGA",
   REQUEST_ADRESS_SAGA = "REQUEST_ADRESS_SAGA",
   REQUEST_ORDER_SAGA = "REQUEST_ORDER_SAGA",
}