#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# PROJECT
echo
echo 🚀 Checking the name of the last commit
yarn commit
echo
echo 🚀 Checking the name of branch
yarn branch

# FRONTEND
if [ -d client/node_modules ]; then
    echo
    echo 🚀 Running checks for client
    cd client
    yarn check:all
    cd ..
fi

# BACKEND
if [ -d server/node_modules ]; then
    echo
    echo 🚀 running checks for server
    cd server
    yarn lint
fi

exit 0
