name: CI

on:
    pull_request:
        types: ["opened", "edited"]
    push:

jobs:
    commit:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18.x]
        steps:
            - name: Get repository code
              uses: actions/checkout@v3
            - name: Staring Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install dependencies for project
              run: |
                  yarn install
            - name: Run husky
              run: |
                  yarn branch-name-lint branch-name-lint.json
    init:
        runs-on: ubuntu-latest
        steps:
            - name: Get repository code
              uses: actions/checkout@v3
            - name: Install dependencies for server
              run: |
                  cd server
                  yarn install
            - name: Install dependencies for client
              run: |
                  cd client
                  yarn install
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Get repository code
              uses: actions/checkout@v3
            # - name: Install dependencies for server
            #   run: |
            #       cd server
            #       yarn install
            - name: Run eslint for server
              run: |
                  cd server
                  yarn run lint
            # - name: Get repository code
            #   uses: actions/checkout@v3
            # - name: Install dependencies for client
            #   run: |
            #       cd client
            #       yarn install
            - name: Run stylelint for client
              run: |
                  cd client
                  yarn run stylelint
            - name: Run eslint for client
              run: |
                  cd client
                  yarn run lint
        needs: ["init"]
