name: CI

on:
  push:
    branches:
      - feat/**
      - fix/**
      - refactor/**

jobs:
  project:
    name: Project
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - name: Install dependencies
        run: |
          yarn install
      - name: Checking the branch name
        run: |
          yarn branch
  client:
    name: Client
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - name: Install dependencies
        run: |
          cd client
          yarn install
      - name: Run stylelint
        run: |
          cd client
          yarn styles
      - name: Run eslint
        run: |
          cd client
          yarn lint
      - name: Check TS
        run: |
          cd client
          yarn check:ts
  server:
    name: Server
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - name: Install dependencies
        run: |
          cd server
          yarn install
      - name: Run eslint
        run: |
          cd server
          yarn lint
