name: Github Actions

on:
    push:
        branches:
            - "*"
            - "*/*"
            - "**"
            - "!main"
    pull_request:
        branches: ["main"]

jobs:
    init:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [16.x]
        steps:
            - uses: actions/checkout@v3
            - name: Staring Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install dependencies for client
              run: |
                  cd client
                  yarn install
            - name: Install dependencies for server
              run: |
                  cd server
                  yarn install
    lint:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [16.x]
        steps:
            - name: Run prettier (client)
              run: |
                  cd client
                  yarn run prettier --check "./"
            - name: Run stylelint (client)
              run: |
                  cd client
                  yarn run stylelint
            - name: Run eslint (client)
              run: |
                  cd client
                  yarn run lint
            - name: Run eslint (server)
              run: |
                  cd server
                  yarn run lint
        needs: ["init"]
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [16.x]
        steps:
            - name: Build project (client)
              run: |
                  cd client
                  yarn run build
        needs: ["init", "lint"]
