name: Versioning

on:
  push:
    branches: [main]

jobs:
  bumpVersion:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - name: Init
        run: |
          git config --global user.email github-actions[bot]
          git config --global user.name github-actions[bot]@users.noreply.github.com
      - name: Update version of Clever Shop!
        run: |
          npm version patch -m "Version upgraded! It's %s version now"
          git push --follow-tags
